name: flutter_onboard
description: A simple, elegant and easy to use onboard widget for both android and ios devices(Null-Safety).
version: 2.0.0
homepage: https://github.com/mohanasundaramn/ms-flutter-packages
repository: https://github.com/mohanasundaramn/ms-flutter-packages/tree/master/flutter_onboard

environment:
  sdk: ">=3.0.0 <3.22.3"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.2
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  freezed: ^2.5.2
  build_runner: ^2.4.11
flutter:
